### PR TITLE
Ts/transducer methods

### PR DESCRIPTION
**Pull request by TomShacham**
* filterNot is on the contract, chunk and partitionBy are only on transducer atm.
* they are also very imperative *ahem* performant I mean. happy to throw away for a more functional approach

### CODE REVIEW

**Comment by TomShacham** [comment]
* renamed filterNot to reject
* add chunk and partitionBy to Sequence and AsyncSequence

bug: `range(1).partitionBy(() => true).take(10).toArray()` runs forever i.e. `partitionBy` is eager not lazy

`chunk` does not have this problem

**Comment by TomShacham** [comment]
* adds reverse, drop, dropWhile
* however, reverse is eager :(

**Comment by danielbodart** [comment]
Okay so far I'd like to take "reject, drop, dropWhile". I've tried cherry picking from your PR but it just won't do it as git is just not very good at patches!

So either I do it manually then you will have a nightmare merging, or you seperate them into different PRs

I'm not sure about partitionby as I've never once had a use case for it, while i use group(by) all the time. Chunk I like but the implementation seems odd - but I probably just need to try and write it myself.

I doubt if you will get flatten to compile as it requires the typesystem to support instance method with type constrains (i.e you can only call flatten on a Sequence<A> where A extends Sequence<?>)

**Comment by TomShacham** [comment]
☝️ oh i also removed flatten

**Comment by danielbodart** [comment]
Ooops I need to get pull request building on circleci, as this just failed to compile! 

You need to update your fork

**Pull request merged**
